#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <windows.h>
#define N 9

// ANSI escape codes for text color (Windows)
#define COLOR_RESET "\033[0m"
#define COLOR_YELLOW "\033[1;33m"
#define COLOR_CYAN "\033[1;36m"

void printGrid(int grid[N][N])
{
    printf(" -------------------------------------------\n");
    for (int i = 0; i < N; i++)
    {
        for (int j = 0; j < N; j++)
        {
            if (j == 0)
            {
                printf(" |");
            }
            printf("%3d ", grid[i][j]);
            if ((j + 1) % 3 == 0)
                printf(" |");
        }
        printf("\n");
        if ((i + 1) % 3 == 0)
        {
            printf(" -------------------------------------------\n");
        }
    }
}

char isValid(int grid[N][N], int row, int col, int num)
{
    for (int i = 0; i < N; i++)
    {
        if (grid[row][i] == num || grid[i][col] == num)
        {
            return 0;
        }
    }
    // Check 3x3 MiniGrid
    int newRow = row - row % 3; /*if row = 5   we start from = 5 - 5%3 = 5 - 3 = 3*/
    int newCol = col - col % 3;
    for (int i = 0; i < 3; i++)
    {
        for (int j = 0; j < 3; j++)
        {
            if (grid[newRow + i][newCol + j] == num)
            {
                return 0;
            }
        }
    }

    return 1;
}

char isCompleted(int grid[N][N])
{
    for (int i = 0; i < N; i++)
    {
        for (int j = 0; j < N; j++)
        {
            if (grid[i][j] == 0)
            {
                return 0;
            }
        }
    }
    return 1;
}

char solveSudoku(int grid[N][N])
{
    for (int row = 0; row < N; row++)
    {
        for (int col = 0; col < N; col++)
        {
            if (grid[row][col] == 0)
            {
                for (int num = 1; num <= N; num++)
                {
                    if (isValid(grid, row, col, num))
                    {
                        grid[row][col] = num;
                        if (solveSudoku(grid))
                        {
                            return 1;
                        }
                        grid[row][col] = 0; // Backtrack
                    }
                }
                return 0;
            }
        }
    }
    return 1; // Puzzle solved
}

void sudukoGenerate(int grid[N][N], int autogenerated[N][N])
{
    srand(time(NULL));
    int c = 0;
    for (int i = 0; i < N; i++)
    {
        for (int j = 0; j < N; j++)
        {
            autogenerated[i][j] = 0;
        }
    }

    for (int i = 0; i < N; i++)
    {
        for (int num = 1; num <= N; num++)
        {
            int randRow = i + rand() % 3;
            int randCol = i + rand() % 3;

            while (!isValid(grid, randRow, randCol, num))
            {
                randRow = i + rand() % 3;
                randCol = i + rand() % 3;
            }

            grid[randRow][randCol] = num;
            autogenerated[randRow][randCol] = 1;
        }
    }
}

void modifySudoku(int grid[N][N], int row, int col, int num, int autogenerated[N][N])
{
    if (row >= 0 && row < N && col >= 0 && col < N && autogenerated[row][col] == 0)
    {
        grid[row][col] = num;
    }
    else
    {
        printf("Invalid move. You can only modify new entered numbers.\n");
    }
}
// Function to print the Sudoku grid with colored new entered numbers
void printColoredGrid(int grid[N][N], int autogenerated[N][N])
{
    printf(" -------------------------------------------\n");
    for (int i = 0; i < N; i++)
    {
        for (int j = 0; j < N; j++)
        {
            if (j == 0)
            {
                printf(" |");
            }
            if (autogenerated[i][j] == 1)
            {
                printf(COLOR_YELLOW "%3d " COLOR_RESET, grid[i][j]); // Print new entered numbers in yellow
            }
            else
            {
                printf(COLOR_CYAN "%3d " COLOR_RESET, grid[i][j]); // Print autogenerated numbers in cyan
            }
            if ((j + 1) % 3 == 0)
            {
                printf(" |");
            }
        }
        printf("\n");
        if ((i + 1) % 3 == 0)
        {
            printf(" -------------------------------------------\n");
        }
    }
}

int main()
{
    int sudokuGrid[N][N] = {{0}};
    int autogenerated[N][N] = {{0}};

    sudukoGenerate(sudokuGrid, autogenerated);

    int exit = 1;
    int row = 0, col = 0, num = 0, solveKey = 0;

    printGrid(sudokuGrid);

    while (exit != 0)
    {
        printf("Enter row and col number (0 to quit):\n");
        scanf("%d%d", &row, &col);

        if (row == 0 || col == 0)
        {
            printf("Quitting the game. Goodbye!\n");
            break;
        }

        if (row < 1 || col < 1 || row > N || col > N)
        {
            printf("Invalid position.... Try again!!\n");
            continue;
        }

        printf("Enter a number from 1-9 in this position [%d][%d]: ", row, col);
        scanf("%d", &num);

        if (num < 1 || num > 9)
        {
            printf("Invalid number.... Try again!!\n");
            continue;
        }

        modifySudoku(sudokuGrid, row - 1, col - 1, num, autogenerated);

        printColoredGrid(sudokuGrid, autogenerated);

        if (isCompleted(sudokuGrid))
        {
            printf("Congratulations! You have completed the Sudoku puzzle!\n");
            exit = 0;
        }
        else
        {
            printf("To continue playing press any Key\nTo Exit press 0\n");
            scanf("%d", &exit);
        }
    }

    printf("Display the Puzzle solution press 2: \n");
    scanf("%d", &solveKey);

    if (solveKey == 2)
    {
        int solutionGrid[N][N];
        for (int i = 0; i < N; i++)
        {
            for (int j = 0; j < N; j++)
            {
                solutionGrid[i][j] = sudokuGrid[i][j];
            }
        }

        if (solveSudoku(solutionGrid))
        {
            printf("\nSudoku puzzle solution:\n");
            printGrid(solutionGrid);
        }
        else
        {
            printf("\nNo solution exists.\n");
        }

        solveSudoku(sudokuGrid);
    }

    printGrid(sudokuGrid);

    return 0;
}
